<?php

namespace App\Http\Livewire\Frontend\Checkout;

use App\Models\Cart;
use Livewire\Component;
use Illuminate\Support\Facades\Auth;

class Index extends Component
{
    public $carts;
    public $pays;
    public $ville;

    public $paysDisponible = [];
    public $villesDisponible = [];

    public function mount()
    {
        if (Auth::guard('etudiant')->check()) {
            $this->carts = Cart::where('etudiant_id', Auth::guard('etudiant')->id())->latest()->get();
        }

        $this->paysDisponible = [
            "Afghanistan",
            "Afrique du Sud",
            "Albanie",
            "Algérie",
            "Allemagne",
            "Andorre",
            "Angola",
            "Arabie Saoudite",
            "Argentine",
            "Arménie",
            "Australie",
            "Autriche",
            "Azerbaïdjan",
            "Bahamas",
            "Bahreïn",
            "Bangladesh",
            "Barbade",
            "Belgique",
            "Bénin",
            "Bhoutan",
            "Biélorussie",
            "Birmanie",
            "Bolivie",
            "Bosnie-Herzégovine",
            "Botswana",
            "Brésil",
            "Brunei",
            "Bulgarie",
            "Burkina Faso",
            "Burundi",
            "Cameroun",
            "Canada",
            "Cap-Vert",
            "Chili",
            "Chine",
            "Chypre",
            "Colombie",
            "Comores",
            "Congo (Brazzaville)",
            "Congo (Kinshasa)",
            "Corée du Nord",
            "Corée du Sud",
            "Costa Rica",
            "Côte d'Ivoire",
            "Croatie",
            "Cuba",
            "Danemark",
            "Djibouti",
            "Dominique",
            "Égypte",
            "Émirats arabes unis",
            "Équateur",
            "Érythrée",
            "Espagne",
            "Estonie",
            "Eswatini",
            "États-Unis",
            "Éthiopie",
            "Fidji",
            "Finlande",
            "France",
            "Gabon",
            "Gambie",
            "Géorgie",
            "Ghana",
            "Grèce",
            "Guatemala",
            "Guinée",
            "Guinée équatoriale",
            "Guinée-Bissau",
            "Guyana",
            "Haïti",
            "Honduras",
            "Hongrie",
            "Inde",
            "Indonésie",
            "Irak",
            "Iran",
            "Irlande",
            "Islande",
            "Israël",
            "Italie",
            "Jamaïque",
            "Japon",
            "Jordanie",
            "Kazakhstan",
            "Kenya",
            "Kirghizistan",
            "Kiribati",
            "Koweït",
            "Laos",
            "Lesotho",
            "Lettonie",
            "Liban",
            "Libéria",
            "Libye",
            "Liechtenstein",
            "Lituanie",
            "Luxembourg",
            "Macédoine du Nord",
            "Madagascar",
            "Malaisie",
            "Malawi",
            "Maldives",
            "Mali",
            "Malte",
            "Maroc",
            "Maurice",
            "Mauritanie",
            "Mexique",
            "Micronésie",
            "Moldavie",
            "Monaco",
            "Mongolie",
            "Monténégro",
            "Mozambique",
            "Namibie",
            "Nauru",
            "Népal",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "Norvège",
            "Nouvelle-Zélande",
            "Oman",
            "Ouganda",
            "Ouzbékistan",
            "Pakistan",
            "Palaos",
            "Palestine",
            "Panama",
            "Papouasie-Nouvelle-Guinée",
            "Paraguay",
            "Pays-Bas",
            "Pérou",
            "Philippines",
            "Pologne",
            "Portugal",
            "Qatar",
            "République Centrafricaine",
            "République tchèque",
            "Roumanie",
            "Royaume-Uni",
            "Russie",
            "Rwanda",
            "Saint-Kitts-et-Nevis",
            "Saint-Marin",
            "Saint-Vincent-et-les-Grenadines",
            "Sainte-Lucie",
            "Salomon",
            "Salvador",
            "Samoa",
            "Sao Tomé-et-Principe",
            "Sénégal",
            "Serbie",
            "Seychelles",
            "Sierra Leone",
            "Singapour",
            "Slovaquie",
            "Slovénie",
            "Somalie",
            "Soudan",
            "Soudan du Sud",
            "Sri Lanka",
            "Suède",
            "Suisse",
            "Suriname",
            "Syrie",
            "Tadjikistan",
            "Tanzanie",
            "Tchad",
            "Thaïlande",
            "Timor oriental",
            "Togo",
            "Tonga",
            "Trinité-et-Tobago",
            "Tunisie",
            "Turkménistan",
            "Turquie",
            "Tuvalu",
            "Ukraine",
            "Uruguay",
            "Vanuatu",
            "Vatican",
            "Venezuela",
            "Viêt Nam",
            "Yémen",
            "Zambie",
            "Zimbabwe"
        ];
    }

    public function updatedPays($pays)
    {
        $this->ville = null;

        $listeVilles = [
            'Afghanistan' => ['Kaboul', 'Kandahar', 'Hérat'],
            'Afrique du Sud' => ['Johannesburg', 'Le Cap', 'Durban'],
            'Albanie' => ['Tirana', 'Durrës', 'Vlorë'],
            'Algérie' => ['Alger', 'Oran', 'Constantine'],
            'Allemagne' => ['Berlin', 'Munich', 'Francfort'],
            'Arabie Saoudite' => ['Riyad', 'Djeddah', 'La Mecque'],
            'Argentine' => ['Buenos Aires', 'Córdoba', 'Rosario'],
            'Australie' => ['Sydney', 'Melbourne', 'Brisbane'],
            'Autriche' => ['Vienne', 'Salzbourg', 'Innsbruck'],
            'Belgique' => ['Bruxelles', 'Anvers', 'Liège'],
            'Brésil' => ['São Paulo', 'Rio de Janeiro', 'Brasília'],
            'Burkina Faso' => ['Ouagadougou', 'Bobo-Dioulasso', 'Koudougou'],
            'Cameroun' => ['Yaoundé', 'Douala', 'Bafoussam'],
            'Canada' => ['Montréal', 'Toronto', 'Vancouver', 'Ottawa'],
            'Chine' => ['Pékin', 'Shanghai', 'Guangzhou'],
            'Côte d\'Ivoire' => ['Abidjan', 'Bouaké', 'Yamoussoukro'],
            'Danemark' => ['Copenhague', 'Aarhus', 'Odense'],
            'Égypte' => ['Le Caire', 'Alexandrie', 'Gizeh'],
            'Espagne' => ['Madrid', 'Barcelone', 'Valence'],
            'États-Unis' => ['New York', 'Los Angeles', 'Chicago', 'Houston'],
            'France' => ['Paris', 'Lyon', 'Marseille', 'Toulouse'],
            'Ghana' => ['Accra', 'Kumasi', 'Tamale'],
            'Grèce' => ['Athènes', 'Thessalonique', 'Patras'],
            'Inde' => ['Delhi', 'Mumbai', 'Bangalore'],
            'Indonésie' => ['Jakarta', 'Surabaya', 'Bandung'],
            'Italie' => ['Rome', 'Milan', 'Naples'],
            'Japon' => ['Tokyo', 'Osaka', 'Kyoto'],
            'Kenya' => ['Nairobi', 'Mombasa', 'Kisumu'],
            'Maroc' => ['Casablanca', 'Rabat', 'Marrakech'],
            'Mali' => ['Bamako', 'Sikasso', 'Kayes', 'Koulikoro'],
            'Mexique' => ['Mexico', 'Guadalajara', 'Monterrey'],
            'Nigéria' => ['Lagos', 'Abuja', 'Kano'],
            'Pays-Bas' => ['Amsterdam', 'Rotterdam', 'La Haye'],
            'Portugal' => ['Lisbonne', 'Porto', 'Braga'],
            'Royaume-Uni' => ['Londres', 'Manchester', 'Birmingham'],
            'Russie' => ['Moscou', 'Saint-Pétersbourg', 'Novossibirsk'],
            'Sénégal' => ['Dakar', 'Thiès', 'Saint-Louis'],
            'Suisse' => ['Zurich', 'Genève', 'Bâle'],
            'Thaïlande' => ['Bangkok', 'Chiang Mai', 'Pattaya'],
            'Tunisie' => ['Tunis', 'Sfax', 'Sousse'],
            'Turquie' => ['Istanbul', 'Ankara', 'Izmir'],
            'Ukraine' => ['Kyiv', 'Lviv', 'Odessa'],
            'Vietnam' => ['Hanoï', 'Hô Chi Minh-Ville', 'Da Nang'],
            'Zimbabwe' => ['Harare', 'Bulawayo', 'Mutare'],
        ];


        $this->villesDisponible = $listeVilles[$pays] ?? [];
    }

    public function render()
    {
        return view('livewire.frontend.checkout.index');
    }
}
